services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.db2
    # image: icr.io/db2_community/db2:latest
    hostname: db2server
    privileged: true
    env_file:
      - .db2.env
    volumes:
      - db2_data:/database
      - ../..:/workspaces:cached
    ports:
      - 50000:50000
    # command: sleep infinity

  # db2console:
  #   image: ibmcom/db2console:latest
  #   container_name: db2console
  #   ports:
  #     - 11081:8443
  #   environment:
  #     - LICENSE=accept

  # db:
  #   image: icr.io/db2_community/db2:latest
  #   hostname: db2server
  #   container_name: db2server
  #   restart: always
  #   privileged: true
  #   env_file:
  #     - .db2.env
  #   ports:
  #     - 50000:50000
  #   volumes:
  #     - db2_data:/database

volumes:
  db2_data:
